version: '3.13'
services:
  api:
    build: .
    ports:
      - 8000:8000
    # # For development environment allow for autorenew code in docker image
    # volumes:
    #   - ./:/usr/src/app
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./.env
    depends_on:
      - postgres
    
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=fastapi

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
