version: '3.13'
services:
  api:
    build: .
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=fastapi

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
